config/routes.rb
Rubynorte::Application.routes.draw do
  resources :admissions
  resources :talks

  get "content/index"
  get "content/map", :as => 'map'

  match "/auth/:provider/callback" => "admissions#create"

  root :to => "content#index"

end

app/models/admission.rb
class Admission < ActiveRecord::Base
end

app/models/talk.rb
class Talk < ActiveRecord::Base
  scope :accepted, where(:accepted => true)
  validates_presence_of :title, :summary, :person
end

app/controllers/admissions_controller.rb
# encoding: utf-8
class AdmissionsController < ApplicationController
  def index
    @admissions = Admission.all
    render :layout => !request.xhr?
  end

  def new
    render :layout => !request.xhr?
  end

  def create
    auth = request.env["omniauth.auth"]
    admission = Admission.find_by_provider_and_uid(auth["provider"], auth["uid"]) ||
      Admission.create!({ provider: auth["provider"] ,
        uid: auth["uid"] ,
        name: auth["user_info"]["name"] ,
        image_url: auth["user_info"]["image"] ,
        screen_name: auth["user_info"]["nickname"]})
    session[:user] = { :provider => admission.provider, :uid => admission.uid, :name => admission.name, :confirmed => admission.confirmed }
    redirect_to root_url, :notice => "Obrigado por te teres inscrito! Estás entre #{Admission.count - 1} outros rubyistas (para já). Traz um amigo!"
  end

  def update
    @admission = Admission.find_by_provider_and_uid session[:user][:provider], session[:user][:uid]
    if @admission.update_attributes params[:admission]
      session[:user][:confirmed] = true
      redirect_to root_url, :notice => "Obrigado por teres confirmado que vens. Ficamos felizes por vires, até lá!"
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/content_controller.rb
class ContentController < ApplicationController
  def index
    @talks = Talk.accepted.order('title')
    @talk  = Talk.new
    @admissions = Admission.order('created_at')
    @confirmed_count = @admissions.map { |ab| ab.confirmed }.count { |ac| ac == true }

    @user = Admission.find_by_provider_and_uid session[:user][:provider], session[:user][:uid] if session[:user]
  end

  def map
    render :layout => false
  end

end

app/controllers/session_controller.rb
# encoding: utf-8
class SessionController < ApplicationController
  def create
    # raise request.env['omniauth.auth'].to_yaml
    auth = request.env["omniauth.auth"]
    admission = Admission.find_by_provider_and_uid(auth["provider"], auth["uid"]) ||
      Admission.create!({ provider: auth["provider"] ,
        uid: auth["uid"] ,
        name: auth["user_info"]["name"] ,
        image_url: auth["user_info"]["image"] ,
        screen_name: auth["user_info"]["nickname"]})
    redirect_to root_url, :notice => "Obrigado por te teres inscrito! Estás entre #{Admission.count - 1} outros rubyistas (para já). Traz um amigo!"
  end

end

app/controllers/talks_controller.rb
class TalksController < ApplicationController
  # GET /talks
  # GET /talks.xml
  before_filter :authenticate, :except => :create

  def index
    @talks = Talk.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @talks }
    end
  end

  # GET /talks/1
  # GET /talks/1.xml
  def show
    @talk = Talk.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @talk }
    end
  end

  # GET /talks/new
  # GET /talks/new.xml
  def new
    @talk = Talk.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @talk }
    end
  end

  # GET /talks/1/edit
  def edit
    @talk = Talk.find(params[:id])
  end

  # POST /talks
  # POST /talks.xml
  def create
    @talk = Talk.new(params[:talk])

    respond_to do |format|
      if @talk.save
        format.html { redirect_to(root_path, :notice => 'A tua apresenta&ccedil;&atilde;o foi submetida e ser&aacute; divulgada em breve! Obrigado pelo teu interesse.') }
        format.xml  { render :xml => @talk, :status => :created, :location => @talk }
      else
        format.html { redirect_to(root_path, :alert => 'Houve um problema a submeter a tua apresenta&ccedil;&atilde;o. Por favor tenta de novo.')}
        format.xml  { render :xml => @talk.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /talks/1
  # PUT /talks/1.xml
  def update
    @talk = Talk.find(params[:id])

    respond_to do |format|
      if @talk.update_attributes(params[:talk])
        format.html { redirect_to(@talk, :notice => 'Talk was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @talk.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /talks/1
  # DELETE /talks/1.xml
  def destroy
    @talk = Talk.find(params[:id])
    @talk.destroy

    respond_to do |format|
      format.html { redirect_to(talks_url) }
      format.xml  { head :ok }
    end
  end

  private
  def authenticate
    authenticate_or_request_with_http_basic do |u,p|
      u == 'superuser' && p == 'rubynorte2011'
    end
  end
end

app/helpers/admissions_helper.rb
module AdmissionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/content_helper.rb
module ContentHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/talks_helper.rb
module TalksHelper
end

app/views/admissions/create.html.haml
%h1 Admissions#create
%p Find me in app/views/admissions/create.html.haml

app/views/admissions/index.html.haml
%h1 Admissions#index
%p Find me in app/views/admissions/index.html.haml

app/views/admissions/new.html.haml
%h1 Regista-te via Twitter!

app/views/content/index.html.haml
-if session[:user] && !session[:user][:confirmed]
  #confirm-admission
    %p Confirmas que apareces no Rubynorte no dia 21?
    -form_for @user do |f|
      =f.hidden_field :confirmed, :value => 1
      =f.submit 'Confirmo!'


#splash
  .half
    %h1 Ruby, Rails, Sinatra... em Portugal.

    %p
      Rubynorte é o encontro para todos aqueles que querem aprender mais sobre
      a linguagem de programação Ruby.
  
  .half=image_tag "/images/rn1.png",:alt => "1 encontro Ruby Norte"
  
#about

  %h2
    No último evento tivemos inscritas
    ="#{pluralize @admissions.count, "pessoa"},"
    =@confirmed_count
    confirmadas.

  %ul#admissions
    -@admissions.each do |admission|
      %li{:class => admission.confirmed ? 'confirmed' : '' }
        =link_to image_tag(admission.image_url, :width => '40'),"http://twitter.com/#{admission.screen_name}",:title => admission.name

-@talks.each do |talk|
  .speaker
    %img(width='180' height='135')
    %h1=talk.title
    %h2=talk.person
    %p=talk.summary

app/views/content/map.html.erb
<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.pt/maps?f=q&amp;source=s_q&amp;hl=pt-PT&amp;q=praceta+sao+pedro&amp;aq=&amp;sll=41.14477,-8.644851&amp;sspn=0.001174,0.002411&amp;ie=UTF8&amp;t=h&amp;rq=1&amp;ev=p&amp;split=1&amp;radius=0.08&amp;hq=praceta+sao+pedro&amp;hnear=&amp;ll=41.145344,-8.644867&amp;spn=0.011311,0.018239&amp;z=15&amp;iwloc=A&amp;output=embed"></iframe>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Rubynorte | Conferência de Ruby no Porto, Portugal.
    = stylesheet_link_tag :all
    = stylesheet_link_tag 'fancybox/fancybox'
    = javascript_include_tag :defaults
  %body
    %header
      %div
        %h1 Ruby Norte
      =content_tag :div, raw(notice), :class => 'flash notice' if notice
      =content_tag :div, raw(alert), :class => 'flash alert' if alert
    #bucket
      #main= yield
      %footer
        %p
          Segue-nos no Twitter pela hash
          =link_to "#rubynorte", "https://twitter.com/#search?q=rubynorte"
          ou segue o
          =link_to "@rubynorte", "http://twitter.com/rubynorte"
          !

app/views/session/create.html.haml
%h1 Session#create
%p Find me in app/views/session/create.html.haml

app/views/session/destroy.html.haml
%h1 Session#destroy
%p Find me in app/views/session/destroy.html.haml

app/views/talks/_form.html.haml
= form_for @talk do |f|
  -if @talk.errors.any?
    #error_explanation
      %h2= "#{pluralize(@talk.errors.count, "error")} prohibited this talk from being saved:"
      %ul
        - @talk.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :person
    = f.text_field :person
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :summary
    = f.text_area :summary
  .field
    = f.label :accepted
    = f.check_box :accepted
  .actions
    = f.submit 'Save'

app/views/talks/edit.html.haml
%h1 Editing talk

= render 'form'

= link_to 'Show', @talk
\|
= link_to 'Back', talks_path

app/views/talks/index.html.haml
%h1 Listing talks

%table
  %tr
    %th Person
    %th Title
    %th Summary
    %th
    %th
    %th

  - @talks.each do |talk|
    %tr
      %td= talk.person
      %td= talk.title
      %td= talk.summary
      %td= link_to 'Show', talk
      %td= link_to 'Edit', edit_talk_path(talk)
      %td= link_to 'Destroy', talk, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Talk', new_talk_path

app/views/talks/new.html.haml
%h1 New talk

= render 'form'

= link_to 'Back', talks_path

app/views/talks/show.html.haml
%p#notice= notice

%p
  %b Person:
  = @talk.person
%p
  %b Title:
  = @talk.title
%p
  %b Summary:
  = @talk.summary

= link_to 'Edit', edit_talk_path(@talk)
\|
= link_to 'Back', talks_path